src/Entity/Tafel.php
<?php

namespace App\Entity;

use App\Repository\TafelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TafelRepository::class)
 */
class Tafel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $tafel_nr;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_personen;

    /**
     * @ORM\OneToMany(targetEntity=Reservering::class, mappedBy="tafel")
     */
    private $reserverings;

    public function __construct()
    {
        $this->reserverings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTafelNr(): ?int
    {
        return $this->tafel_nr;
    }

    public function setTafelNr(int $tafel_nr): self
    {
        $this->tafel_nr = $tafel_nr;

        return $this;
    }

    public function getMaxPersonen(): ?int
    {
        return $this->max_personen;
    }

    public function setMaxPersonen(int $max_personen): self
    {
        $this->max_personen = $max_personen;

        return $this;
    }

    /**
     * @return Collection|Reservering[]
     */
    public function getReserverings(): Collection
    {
        return $this->reserverings;
    }

    public function addReservering(Reservering $reservering): self
    {
        if (!$this->reserverings->contains($reservering)) {
            $this->reserverings[] = $reservering;
            $reservering->setTafel($this);
        }

        return $this;
    }

    public function removeReservering(Reservering $reservering): self
    {
        if ($this->reserverings->removeElement($reservering)) {
            // set the owning side to null (unless already changed)
            if ($reservering->getTafel() === $this) {
                $reservering->setTafel(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->getTafelNr().", max. ".$this->max_personen." personen";
    }
}

src/Form/TafelType.php
<?php

namespace App\Form;

use App\Entity\Tafel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TafelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tafel_nr')
            ->add('max_personen')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tafel::class,
        ]);
    }
}

src/Controller/TafelController.php
<?php

namespace App\Controller;

use App\Entity\Tafel;
use App\Form\TafelType;
use App\Repository\TafelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tafel")
 */
class TafelController extends AbstractController
{
    /**
     * @Route("/", name="tafel_index", methods={"GET"})
     */
    public function index(TafelRepository $tafelRepository): Response
    {
        return $this->render('tafel/index.html.twig', [
            'tafels' => $tafelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="tafel_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tafel = new Tafel();
        $form = $this->createForm(TafelType::class, $tafel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tafel);
            $entityManager->flush();

            return $this->redirectToRoute('tafel_index');
        }

        return $this->render('tafel/new.html.twig', [
            'tafel' => $tafel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tafel_show", methods={"GET"})
     */
    public function show(Tafel $tafel): Response
    {
        return $this->render('tafel/show.html.twig', [
            'tafel' => $tafel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tafel_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tafel $tafel): Response
    {
        $form = $this->createForm(TafelType::class, $tafel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tafel_index');
        }

        return $this->render('tafel/edit.html.twig', [
            'tafel' => $tafel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tafel_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tafel $tafel): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tafel->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tafel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tafel_index');
    }
}

templates/tafel/_delete_form.html.twig
<form method="post" action="{{ path('tafel_delete', {'id': tafel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tafel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tafel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tafel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tafel{% endblock %}

{% block body %}
    <h1>Edit Tafel</h1>

    {{ include('tafel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tafel_index') }}">back to list</a>

    {{ include('tafel/_delete_form.html.twig') }}
{% endblock %}

templates/tafel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tafel index{% endblock %}

{% block body %}
    <h1>Tafel index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tafel_nr</th>
                <th>Max_personen</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tafel in tafels %}
            <tr>
                <td>{{ tafel.id }}</td>
                <td>{{ tafel.tafelNr }}</td>
                <td>{{ tafel.maxPersonen }}</td>
                <td>
                    <a href="{{ path('tafel_show', {'id': tafel.id}) }}">show</a>
                    <a href="{{ path('tafel_edit', {'id': tafel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tafel_new') }}">Create new</a>
{% endblock %}

templates/tafel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tafel{% endblock %}

{% block body %}
    <h1>Create new Tafel</h1>

    {{ include('tafel/_form.html.twig') }}

    <a href="{{ path('tafel_index') }}">back to list</a>
{% endblock %}

templates/tafel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tafel{% endblock %}

{% block body %}
    <h1>Tafel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tafel.id }}</td>
            </tr>
            <tr>
                <th>Tafel_nr</th>
                <td>{{ tafel.tafelNr }}</td>
            </tr>
            <tr>
                <th>Max_personen</th>
                <td>{{ tafel.maxPersonen }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('tafel_index') }}">back to list</a>

    <a href="{{ path('tafel_edit', {'id': tafel.id}) }}">edit</a>

    {{ include('tafel/_delete_form.html.twig') }}
{% endblock %}