src/Entity/Reservering.php
<?php

namespace App\Entity;

use App\Repository\ReserveringRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReserveringRepository::class)
 */
class Reservering
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datum_tijd;

    /**
     * @ORM\Column(type="integer")
     */
    private $aantal_personen;

    /**
     * @ORM\ManyToOne(targetEntity=Klant::class, inversedBy="reserverings")
     */
    private $klant;

    /**
     * @ORM\ManyToOne(targetEntity=Tafel::class, inversedBy="reserverings")
     */
    private $tafel;

    /**
     * @ORM\OneToMany(targetEntity=Bestelling::class, mappedBy="reservering")
     */
    private $bestellings;

    /**
     * @ORM\OneToMany(targetEntity=Bon::class, mappedBy="reservering")
     */
    private $bons;

    public function __construct()
    {
        $this->bestellings = new ArrayCollection();
        $this->bons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatumTijd(): ?\DateTimeInterface
    {
        return $this->datum_tijd;
    }

    public function setDatumTijd(\DateTimeInterface $datum_tijd): self
    {
        $this->datum_tijd = $datum_tijd;

        return $this;
    }

    public function getAantalPersonen(): ?int
    {
        return $this->aantal_personen;
    }

    public function setAantalPersonen(int $aantal_personen): self
    {
        $this->aantal_personen = $aantal_personen;

        return $this;
    }

    public function getKlant(): ?Klant
    {
        return $this->klant;
    }

    public function setKlant(?Klant $klant): self
    {
        $this->klant = $klant;

        return $this;
    }

    public function getTafel(): ?Tafel
    {
        return $this->tafel;
    }

    public function setTafel(?Tafel $tafel): self
    {
        $this->tafel = $tafel;

        return $this;
    }

    /**
     * @return Collection|Bestelling[]
     */
    public function getBestellings(): Collection
    {
        return $this->bestellings;
    }

    public function addBestelling(Bestelling $bestelling): self
    {
        if (!$this->bestellings->contains($bestelling)) {
            $this->bestellings[] = $bestelling;
            $bestelling->setReservering($this);
        }

        return $this;
    }

    public function removeBestelling(Bestelling $bestelling): self
    {
        if ($this->bestellings->removeElement($bestelling)) {
            // set the owning side to null (unless already changed)
            if ($bestelling->getReservering() === $this) {
                $bestelling->setReservering(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Bon[]
     */
    public function getBons(): Collection
    {
        return $this->bons;
    }

    public function addBon(Bon $bon): self
    {
        if (!$this->bons->contains($bon)) {
            $this->bons[] = $bon;
            $bon->setReservering($this);
        }

        return $this;
    }

    public function removeBon(Bon $bon): self
    {
        if ($this->bons->removeElement($bon)) {
            // set the owning side to null (unless already changed)
            if ($bon->getReservering() === $this) {
                $bon->setReservering(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->getId().", ".$this->getKlant();
    }
}

src/Form/ReserveringType.php
<?php

namespace App\Form;

use App\Entity\Reservering;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReserveringType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('datum_tijd')
            ->add('aantal_personen')
            ->add('klant')
            ->add('tafel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservering::class,
        ]);
    }
}

src/Controller/ReserveringController.php
<?php

namespace App\Controller;

use App\Entity\Reservering;
use App\Form\ReserveringType;
use App\Repository\ReserveringRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservering")
 */
class ReserveringController extends AbstractController
{
    /**
     * @Route("/", name="reservering_index", methods={"GET"})
     */
    public function index(ReserveringRepository $reserveringRepository): Response
    {
        return $this->render('reservering/index.html.twig', [
            'reserverings' => $reserveringRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reservering_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservering = new Reservering();
        $form = $this->createForm(ReserveringType::class, $reservering);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservering);
            $entityManager->flush();

            return $this->redirectToRoute('reservering_index');
        }

        return $this->render('reservering/new.html.twig', [
            'reservering' => $reservering,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservering_show", methods={"GET"})
     */
    public function show(Reservering $reservering): Response
    {
        return $this->render('reservering/show.html.twig', [
            'reservering' => $reservering,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservering_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservering $reservering): Response
    {
        $form = $this->createForm(ReserveringType::class, $reservering);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservering_index');
        }

        return $this->render('reservering/edit.html.twig', [
            'reservering' => $reservering,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservering_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservering $reservering): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservering->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservering);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservering_index');
    }
}

templates/reservering/_delete_form.html.twig
<form method="post" action="{{ path('reservering_delete', {'id': reservering.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservering.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservering/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservering/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservering{% endblock %}

{% block body %}
    <h1>Edit Reservering</h1>

    {{ include('reservering/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservering_index') }}">back to list</a>

    {{ include('reservering/_delete_form.html.twig') }}
{% endblock %}

templates/reservering/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservering index{% endblock %}

{% block body %}
    <h1>Reservering index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Datum_tijd</th>
                <th>Aantal_personen</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservering in reserverings %}
            <tr>
                <td>{{ reservering.id }}</td>
                <td>{{ reservering.datumTijd ? reservering.datumTijd|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservering.aantalPersonen }}</td>
                <td>
                    <a href="{{ path('reservering_show', {'id': reservering.id}) }}">show</a>
                    <a href="{{ path('reservering_edit', {'id': reservering.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reservering_new') }}">Create new</a>
{% endblock %}

templates/reservering/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservering{% endblock %}

{% block body %}
    <h1>Create new Reservering</h1>

    {{ include('reservering/_form.html.twig') }}

    <a href="{{ path('reservering_index') }}">back to list</a>
{% endblock %}

templates/reservering/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservering{% endblock %}

{% block body %}
    <h1>Reservering</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservering.id }}</td>
            </tr>
            <tr>
                <th>Datum_tijd</th>
                <td>{{ reservering.datumTijd ? reservering.datumTijd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Aantal_personen</th>
                <td>{{ reservering.aantalPersonen }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservering_index') }}">back to list</a>

    <a href="{{ path('reservering_edit', {'id': reservering.id}) }}">edit</a>

    {{ include('reservering/_delete_form.html.twig') }}
{% endblock %}