src/Entity/Bestelling.php
<?php

namespace App\Entity;

use App\Repository\BestellingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BestellingRepository::class)
 */
class Bestelling
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $aantal;

    /**
     * @ORM\ManyToOne(targetEntity=MenuItem::class, inversedBy="bestellings")
     */
    private $menuitem;

    /**
     * @ORM\ManyToOne(targetEntity=Reservering::class, inversedBy="bestellings")
     */
    private $reservering;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $staat_klaar;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAantal(): ?int
    {
        return $this->aantal;
    }

    public function setAantal(int $aantal): self
    {
        $this->aantal = $aantal;

        return $this;
    }

    public function getMenuitem(): ?MenuItem
    {
        return $this->menuitem;
    }

    public function setMenuitem(?MenuItem $menuitem): self
    {
        $this->menuitem = $menuitem;

        return $this;
    }

    public function getReservering(): ?Reservering
    {
        return $this->reservering;
    }

    public function setReservering(?Reservering $reservering): self
    {
        $this->reservering = $reservering;

        return $this;
    }

    public function getStaatKlaar(): ?bool
    {
        return $this->staat_klaar;
    }

    public function setStaatKlaar(?bool $staat_klaar): self
    {
        $this->staat_klaar = $staat_klaar;

        return $this;
    }
    public function __toString()
    {
        return $this->id.'->'.$this->getMenuitem();
    }
}

src/Form/BestellingType.php
<?php

namespace App\Form;

use App\Entity\Bestelling;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BestellingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('aantal')
            ->add('staat_klaar')
            ->add('menuitem')
            ->add('reservering')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Bestelling::class,
        ]);
    }
}

src/Controller/BestellingController.php
<?php

namespace App\Controller;

use App\Entity\Bestelling;
use App\Form\BestellingType;
use App\Repository\BestellingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bestelling")
 */
class BestellingController extends AbstractController
{
    /**
     * @Route("/", name="bestelling_index", methods={"GET"})
     */
    public function index(BestellingRepository $bestellingRepository): Response
    {
        return $this->render('bestelling/index.html.twig', [
            'bestellings' => $bestellingRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="bestelling_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $bestelling = new Bestelling();
        $form = $this->createForm(BestellingType::class, $bestelling);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bestelling);
            $entityManager->flush();

            return $this->redirectToRoute('bestelling_index');
        }

        return $this->render('bestelling/new.html.twig', [
            'bestelling' => $bestelling,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bestelling_show", methods={"GET"})
     */
    public function show(Bestelling $bestelling): Response
    {
        return $this->render('bestelling/show.html.twig', [
            'bestelling' => $bestelling,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="bestelling_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Bestelling $bestelling): Response
    {
        $form = $this->createForm(BestellingType::class, $bestelling);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('bestelling_index');
        }

        return $this->render('bestelling/edit.html.twig', [
            'bestelling' => $bestelling,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bestelling_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Bestelling $bestelling): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bestelling->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bestelling);
            $entityManager->flush();
        }

        return $this->redirectToRoute('bestelling_index');
    }
}

templates/bestelling/_delete_form.html.twig
<form method="post" action="{{ path('bestelling_delete', {'id': bestelling.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bestelling.id) }}">
    <button class="btn">Delete</button>
</form>

templates/bestelling/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/bestelling/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Bestelling{% endblock %}

{% block body %}
    <h1>Edit Bestelling</h1>

    {{ include('bestelling/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('bestelling_index') }}">back to list</a>

    {{ include('bestelling/_delete_form.html.twig') }}
{% endblock %}

templates/bestelling/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bestelling index{% endblock %}

{% block body %}
    <h1>Bestelling index</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Aantal</th>
            <th>Staat_klaar</th>
            <th>Menu</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for bestelling in bestellings %}
            {% if bestelling.staatKlaar == 1 %}
            <tr>
                <td>{{ bestelling.id }}</td>
                <td>{{ bestelling.aantal }}</td>
                <td>{{ (bestelling.staatKlaar ? "Ja" : "Nee") }}</td>
                <td>{{ bestelling.menuitem }}</td>
                <td>
                    <a href="{{ path('bestelling_show', {'id': bestelling.id}) }}">show</a>
                    <a href="{{ path('bestelling_edit', {'id': bestelling.id}) }}">edit</a>
                </td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Aantal</th>
                <th>Staat_klaar</th>
                <th>Menu</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for bestelling in bestellings %}
            {% if bestelling.staatKlaar == 0 %}
            <tr>
                <td>{{ bestelling.id }}</td>
                <td>{{ bestelling.aantal }}</td>
                <td>{{ (bestelling.staatKlaar ? "Ja" : "Nee") }}</td>
                <td>{{ bestelling.menuitem }}</td>
                <td>
                    <a href="{{ path('bestelling_show', {'id': bestelling.id}) }}">show</a>
                    <a href="{{ path('bestelling_edit', {'id': bestelling.id}) }}">edit</a>
                </td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('bestelling_new') }}">Create new</a>
{% endblock %}

templates/bestelling/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Bestelling{% endblock %}

{% block body %}
    <h1>Create new Bestelling</h1>

    {{ include('bestelling/_form.html.twig') }}

    <a href="{{ path('bestelling_index') }}">back to list</a>
{% endblock %}

templates/bestelling/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bestelling{% endblock %}

{% block body %}
    <h1>Bestelling</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ bestelling.id }}</td>
            </tr>
            <tr>
                <th>Aantal</th>
                <td>{{ bestelling.aantal }}</td>
            </tr>
            <tr>
                <th>Staat_klaar</th>
                <td>{{ bestelling.staatKlaar }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('bestelling_index') }}">back to list</a>

    <a href="{{ path('bestelling_edit', {'id': bestelling.id}) }}">edit</a>

    {{ include('bestelling/_delete_form.html.twig') }}
{% endblock %}